image: maven:latest

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean test
  artifacts:
    paths:
      - target/
  only:
    - merge_requests

deploy:
  stage: deploy
  script:
    - # Adicione os comandos de deploy aqui
  only:
    - master
